#!/usr/bin/env bash
set -euo pipefail

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium

# https://github.com/berkeley-dsep-infra/datahub/issues/5827
git config --system pull.rebase false

# Install VS Code extensions.
# This is not reproducible, and it can be difficult to version these.
export VSCODE_EXTENSIONS=${CONDA_PREFIX}/share/code-server/extensions
mkdir -p ${VSCODE_EXTENSIONS}

for x in \
  ms-toolsai.jupyter \
  ms-python.python \
  quarto.quarto \
  continue.continue \
  ms-vscode.live-server \
  posit.shiny \
  reditorsupport.r \
  ; do
    code-server --extensions-dir ${VSCODE_EXTENSIONS} --install-extension $x
done
