#!/usr/bin/env bash
set -euo pipefail

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium

# https://github.com/berkeley-dsep-infra/datahub/issues/5827
git config --system pull.rebase false

## Install VS Code extensions.

# code-server's conda package assets are installed in share/code-server.
export VSCODE_EXTENSIONS=${CONDA_DIR}/envs/notebook/share/code-server/extensions
mkdir -p ${VSCODE_EXTENSIONS}

# This is not reproducible, and it can be difficult to version these.
for x in \
  ms-toolsai.jupyter \
  ms-python.python \
  quarto.quarto \
  continue.continue \
  ms-vscode.live-server \
  posit.shiny \
  reditorsupport.r \
  ; do
    code-server --extensions-dir ${VSCODE_EXTENSIONS} --install-extension $x
done
      for notebook in image-tests/*.ipynb; do
          jupyter nbconvert --to webpdf "$notebook"
          if [ ! -f "${notebook%.ipynb}.pdf" ]; then
              echo "Error: PDF conversion failed for $notebook"
              exit 1
          fi
      done
